### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by javierforero**
@droberts84

Hi David,

So I wanted to add a custom field "name" to my authentication. In the documentation it says I need to create a controller that inherits from ```Devise::RegistrationsController``` to override the out of the box controller. I have done so in this PR, but I am still getting error when creating a user.

So far I am running this command in the terminal:

```
curl -X POST -v -H 'Content-Type: application/json' http://localhost:3000/auth/  -d '{"name": "John","email": "john@gmail.com", "password": "12345Tri", "password_confirmation":"12345Tri" }'
```

This sends back a 500 error; nonetheless, it creates my user. I know this because I ran ```rails c``` and did ```User.all``` and this created the user. 

My server logs show this 

```
Started POST "/auth/" for ::1 at 2016-11-26 12:54:54 -0600
  ActiveRecord::SchemaMigration Load (1.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by RegistrationsController#create as */*
  Parameters: {"name"=>"John", "email"=>"john@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "registration"=>{"name"=>"John", "email"=>"john@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}}
   (0.2ms)  BEGIN
   (1.4ms)  SELECT COUNT(*) FROM "users" WHERE "users"."provider" = $1 AND "users"."email" = $2  [["provider", "email"], ["email", "john@gmail.com"]]
  SQL (0.9ms)  INSERT INTO "users" ("name", "created_at", "updated_at", "uid", "encrypted_password", "confirmation_token", "confirmation_sent_at", "email", "tokens") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["name", "John"], ["created_at", 2016-11-26 18:54:54 UTC], ["updated_at", 2016-11-26 18:54:54 UTC], ["uid", "john@gmail.com"], ["encrypted_password", "$2a$10$.EA7WdtLTEW8BaW.dAuvT.QqjQJ83.1WVnGhuf5p2F.wXyBlzs2Uq"], ["confirmation_token", "XBCz1zxK_8XqPkR73bzu"], ["confirmation_sent_at", 2016-11-26 18:54:54 UTC], ["email", "john@gmail.com"], ["tokens", "{}"]]
   (2.0ms)  COMMIT
Completed 500 Internal Server Error in 214ms (ActiveRecord: 7.7ms)



NameError (undefined local variable or method `flash' for #<RegistrationsController:0x007f8aa7a65610>):

devise (4.2.0) app/controllers/devise_controller.rb:157:in `set_flash_message'
devise (4.2.0) app/controllers/devise_controller.rb:164:in `set_flash_message!'
devise (4.2.0) app/controllers/devise/registrations_controller.rb:25:in `create'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

it seems like there's an error with a built-in functionality to send a message upon creation. Have you ran into this error before?

### CODE REVIEW

**Comment by drobtravels** [comment]
Did you see this line? What is the flash? Is it applicable for an API
project?

NameError (undefined local variable or method `flash' for
#<RegistrationsController:0x007f8aa7a65610>):

**Comment by javierforero** [comment]
Yeah, I did see that. No, its not applicable. It was in the documentation. I'm such a dummy.  Since I am using the api only I don't need the flash messages. To disable them I had to create a ```config/initializers/devise.rb``` file and add this config:

```
Devise.setup do |config|
  config.navigational_formats = [:json]
end
```

**Comment by javierforero** [comment]
@droberts84 
 
Hi,

So now I am trying to get mailcatcher to work, but its not working.

So I have installed it per these [instructions](https://mailcatcher.me/) and it was successful.
When I run ```mailcatcher``` I get:

```
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://127.0.0.1:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

Now in my ```config/enviroments/development.rb```

per [devise auth documentation](https://github.com/lynndylanhurley/devise_token_auth#email-authentication) I have: 

```
  config.action_mailer.default_url_options = { host: 'localhost' }
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    :address => 'localhost',
    :port => '1025' 
  }

```

but I still get no email when I register a user. I am basically resetting the db everytime so I can run this command to test:

```curl -X POST -v -H 'Content-Type: application/json' http://localhost:3000/auth/  -d '{"name": "Javier","email": "javierforero01@gmail.com", "password": "12345Tri", "password_confirmation":"12345Tri" }'
```

please see my latest commit 'trying to get mailcatcher to work' for all the details

**Comment by drobtravels** [comment]
I don't see anything wrong with your code, but I'm not familiar with mailcatcher.

My uneducated hunch is that something else is wrong, likely with one of your Devise views.  IE its trying to use a path which doesn't exist.  What shows in the console?  Does it show an e-mail being sent?

Another thing you can try is sometimes you need to use 127.0.0.1 instead of localhost.  I assume mailcacther is running?

FWIW, I usually test mailers with [Letter Opender](https://github.com/ryanb/letter_opener) which isn't as cool, but much simpler.

**Pull request merged**
